#!/bin/bash
#Description : For Install Zabbix4.0 on centos7.5
##Author : herbiel

setenforce 0
yum install wget -y
#Set YUM Repository
wget -O CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
rpm -i https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
#install zabbix server and httpd php mysql
yum install zabbix-server-mysql zabbix-web-mysql zabbix-agent mariadb-server -y
systemctl enable mariadb
systemctl start mariadb
# Create zabbix database
mysql -e 'create database zabbix character set utf8 collate utf8_bin;'
mysql -e 'grant all privileges on zabbix.* to zabbix@localhost identified by "zabbix";'
zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -pzabbix zabbix
## set zabbix_server config
sed -i '125a DBPassword=zabbix' /etc/zabbix/zabbix_server.conf
sed -i '18a php_value date.timezone Asia/Shanghai' /etc/httpd/conf.d/zabbix.conf
##
yum install -y wqy-microhei-fonts
\cp  /usr/share/fonts/wqy-microhei/wqy-microhei.ttc /usr/share/fonts/dejavu/DejaVuSans.ttf
##start server
systemctl start zabbix-server
systemctl start httpd
systemctl enable zabbix-server
systemctl enable httpd
